Feature/qa1
DSM-DMS/SMS-Front-V1 pull request #97
Opened 2021-04-12 14:21 UTC by YeongG

# 제목
qa 버그 수정
## 목적
QA에서 발생한 버그를 수정하기 위함
## 상세
공지사항 버그해결
## 영향
## 관련 pr(선택)

2021-04-12 14:32 UTC, LeeSeongJinCa requested changes
저 뒷북? 인거 같아서 죄송한데
Router 건드리시길래 말씀드리자면

`https://dsm-sms.com/notice/announcement-` 와 같이 router 건드려야 할 곳 많은데 이번에 전체적으로 바꿔주시면 감사하겠습니다.

2021-04-12 14:32 UTC, LeeSeongJinCa commented on src/GlobalStyle.ts
> +  }
이거 뭐에요?
.ce-header가 뭐에요?

2021-04-12 14:32 UTC, LeeSeongJinCa commented on src/routers/MainRouter.tsx
> +      <Redirect to="/home" />
이거 필요 없지 않나요?
App.tsx에 
`<Redirect path="/" to="/home" />` 코드 존재합니다.

2021-04-15 02:30 UTC, YeongG commented on src/GlobalStyle.ts
> +  }
Editor.js에서 제공해주는 에디터 style에 들어가는 className인데 스타일 바꿔달라  그래서요

2021-04-15 04:41 UTC, LeeSeongJinCa approved these changes
굳

2021-04-15 04:42 UTC, merged